# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FlyRightAirlines2pt5.ui'
#
# Created: Fri Apr 10 01:22:23 2015
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(755, 673)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../.designer/backup/air_plane_airport.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.lookupTab = QtGui.QWidget()
        self.lookupTab.setObjectName(_fromUtf8("lookupTab"))
        self.bannerImageWidget = QtGui.QWidget(self.lookupTab)
        self.bannerImageWidget.setGeometry(QtCore.QRect(9, 150, 713, 443))
        self.bannerImageWidget.setObjectName(_fromUtf8("bannerImageWidget"))
        self.gridLayout_23 = QtGui.QGridLayout(self.bannerImageWidget)
        self.gridLayout_23.setMargin(0)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.gridGroupBox = QtGui.QGroupBox(self.bannerImageWidget)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridGroupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.widget = QtGui.QWidget(self.gridGroupBox)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_9 = QtGui.QGridLayout(self.widget)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lookupButton = QtGui.QPushButton(self.widget)
        self.lookupButton.setMinimumSize(QtCore.QSize(100, 0))
        self.lookupButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lookupButton.setObjectName(_fromUtf8("lookupButton"))
        self.gridLayout_9.addWidget(self.lookupButton, 7, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_9.addWidget(self.label_3, 2, 4, 1, 1)
        self.lookupButton_2 = QtGui.QPushButton(self.widget)
        self.lookupButton_2.setMinimumSize(QtCore.QSize(100, 0))
        self.lookupButton_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lookupButton_2.setObjectName(_fromUtf8("lookupButton_2"))
        self.gridLayout_9.addWidget(self.lookupButton_2, 0, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_9.addWidget(self.label_2, 2, 3, 1, 1)
        self.resNumLineEdit = QtGui.QLineEdit(self.widget)
        self.resNumLineEdit.setMinimumSize(QtCore.QSize(250, 25))
        self.resNumLineEdit.setObjectName(_fromUtf8("resNumLineEdit"))
        self.gridLayout_9.addWidget(self.resNumLineEdit, 0, 1, 1, 3)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_9.addWidget(self.label_4, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 2, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 655, 160))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_14 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.gridLayout_14.addLayout(self.gridLayout_17, 0, 1, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_14.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_9.addWidget(self.scrollArea, 8, 0, 1, 5)
        self.label_5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_9.addWidget(self.label_5, 1, 3, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.widget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(136, 25))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(139, 16777215))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_9.addWidget(self.lineEdit_3, 3, 4, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(213, 25))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_9.addWidget(self.lineEdit, 3, 3, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.widget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(184, 25))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_9.addWidget(self.lineEdit_2, 3, 0, 1, 1)
        self.nextCommandLink_3 = QtGui.QCommandLinkButton(self.widget)
        self.nextCommandLink_3.setMinimumSize(QtCore.QSize(246, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(20)
        self.nextCommandLink_3.setFont(font)
        self.nextCommandLink_3.setObjectName(_fromUtf8("nextCommandLink_3"))
        self.gridLayout_9.addWidget(self.nextCommandLink_3, 9, 3, 1, 1)
        self.gridLayout_6.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.gridGroupBox, 0, 0, 1, 1)
        self.gridLayoutWidget = QtGui.QWidget(self.lookupTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(99, 29, 531, 125))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/plane.jpg")))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 0, 1, 1, 1)
        self.tabWidget.addTab(self.lookupTab, _fromUtf8(""))
        self.flightInfoTab = QtGui.QWidget()
        self.flightInfoTab.setObjectName(_fromUtf8("flightInfoTab"))
        self.gridLayout_22 = QtGui.QGridLayout(self.flightInfoTab)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.destGroupBox = QtGui.QGroupBox(self.flightInfoTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.destGroupBox.setFont(font)
        self.destGroupBox.setObjectName(_fromUtf8("destGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.destGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.fromLabel = QtGui.QLabel(self.destGroupBox)
        self.fromLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fromLabel.setFont(font)
        self.fromLabel.setObjectName(_fromUtf8("fromLabel"))
        self.gridLayout_4.addWidget(self.fromLabel, 0, 0, 1, 1)
        self.fromComboBox = QtGui.QComboBox(self.destGroupBox)
        self.fromComboBox.setObjectName(_fromUtf8("fromComboBox"))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.setItemText(0, _fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.fromComboBox, 0, 1, 1, 1)
        self.toLabel = QtGui.QLabel(self.destGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.toLabel.setFont(font)
        self.toLabel.setObjectName(_fromUtf8("toLabel"))
        self.gridLayout_4.addWidget(self.toLabel, 1, 0, 1, 1)
        self.toComboBox = QtGui.QComboBox(self.destGroupBox)
        self.toComboBox.setObjectName(_fromUtf8("toComboBox"))
        self.toComboBox.addItem(_fromUtf8(""))
        self.toComboBox.setItemText(0, _fromUtf8(""))
        self.toComboBox.addItem(_fromUtf8(""))
        self.toComboBox.addItem(_fromUtf8(""))
        self.toComboBox.addItem(_fromUtf8(""))
        self.toComboBox.addItem(_fromUtf8(""))
        self.toComboBox.addItem(_fromUtf8(""))
        self.toComboBox.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.toComboBox, 1, 1, 1, 1)
        self.gridLayout_22.addWidget(self.destGroupBox, 0, 0, 1, 1)
        self.passGroupBox = QtGui.QGroupBox(self.flightInfoTab)
        self.passGroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.passGroupBox.setFont(font)
        self.passGroupBox.setObjectName(_fromUtf8("passGroupBox"))
        self.gridLayout_35 = QtGui.QGridLayout(self.passGroupBox)
        self.gridLayout_35.setObjectName(_fromUtf8("gridLayout_35"))
        self.passComboBox = QtGui.QComboBox(self.passGroupBox)
        self.passComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.passComboBox.setObjectName(_fromUtf8("passComboBox"))
        self.passComboBox.addItem(_fromUtf8(""))
        self.passComboBox.setItemText(0, _fromUtf8(""))
        self.passComboBox.addItem(_fromUtf8(""))
        self.passComboBox.addItem(_fromUtf8(""))
        self.passComboBox.addItem(_fromUtf8(""))
        self.passComboBox.addItem(_fromUtf8(""))
        self.passComboBox.addItem(_fromUtf8(""))
        self.passComboBox.addItem(_fromUtf8(""))
        self.passComboBox.addItem(_fromUtf8(""))
        self.passComboBox.addItem(_fromUtf8(""))
        self.gridLayout_35.addWidget(self.passComboBox, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.passGroupBox, 0, 1, 1, 1)
        self.dateTimeGroupBox = QtGui.QGroupBox(self.flightInfoTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dateTimeGroupBox.setFont(font)
        self.dateTimeGroupBox.setObjectName(_fromUtf8("dateTimeGroupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dateTimeGroupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.departDateLabel = QtGui.QLabel(self.dateTimeGroupBox)
        self.departDateLabel.setObjectName(_fromUtf8("departDateLabel"))
        self.gridLayout_5.addWidget(self.departDateLabel, 1, 0, 1, 1)
        self.retDateLabel = QtGui.QLabel(self.dateTimeGroupBox)
        self.retDateLabel.setObjectName(_fromUtf8("retDateLabel"))
        self.gridLayout_5.addWidget(self.retDateLabel, 4, 0, 1, 1)
        self.retDateEdit = QtGui.QDateEdit(self.dateTimeGroupBox)
        self.retDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 3, 1), QtCore.QTime(0, 0, 0)))
        self.retDateEdit.setCalendarPopup(True)
        self.retDateEdit.setObjectName(_fromUtf8("retDateEdit"))
        self.gridLayout_5.addWidget(self.retDateEdit, 5, 0, 1, 1)
        self.departDateEdit = QtGui.QDateEdit(self.dateTimeGroupBox)
        self.departDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 3, 1), QtCore.QTime(0, 0, 0)))
        self.departDateEdit.setTime(QtCore.QTime(0, 0, 0))
        self.departDateEdit.setCalendarPopup(True)
        self.departDateEdit.setObjectName(_fromUtf8("departDateEdit"))
        self.gridLayout_5.addWidget(self.departDateEdit, 2, 0, 1, 1)
        self.departTimeLabel = QtGui.QLabel(self.dateTimeGroupBox)
        self.departTimeLabel.setObjectName(_fromUtf8("departTimeLabel"))
        self.gridLayout_5.addWidget(self.departTimeLabel, 1, 1, 1, 1)
        self.departTimeEdit = QtGui.QTimeEdit(self.dateTimeGroupBox)
        self.departTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(12, 0, 0)))
        self.departTimeEdit.setCalendarPopup(True)
        self.departTimeEdit.setObjectName(_fromUtf8("departTimeEdit"))
        self.gridLayout_5.addWidget(self.departTimeEdit, 2, 1, 1, 1)
        self.returnTimeLabel = QtGui.QLabel(self.dateTimeGroupBox)
        self.returnTimeLabel.setObjectName(_fromUtf8("returnTimeLabel"))
        self.gridLayout_5.addWidget(self.returnTimeLabel, 4, 1, 1, 1)
        self.retTimeEdit = QtGui.QTimeEdit(self.dateTimeGroupBox)
        self.retTimeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(12, 0, 0)))
        self.retTimeEdit.setCalendarPopup(True)
        self.retTimeEdit.setObjectName(_fromUtf8("retTimeEdit"))
        self.gridLayout_5.addWidget(self.retTimeEdit, 5, 1, 1, 1)
        self.fareWidget = QtGui.QWidget(self.dateTimeGroupBox)
        self.fareWidget.setObjectName(_fromUtf8("fareWidget"))
        self.gridLayout = QtGui.QGridLayout(self.fareWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.typeGroupBox = QtGui.QGroupBox(self.fareWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.typeGroupBox.setFont(font)
        self.typeGroupBox.setObjectName(_fromUtf8("typeGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.typeGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.nonStopCheckBox = QtGui.QCheckBox(self.typeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nonStopCheckBox.setFont(font)
        self.nonStopCheckBox.setObjectName(_fromUtf8("nonStopCheckBox"))
        self.gridLayout_3.addWidget(self.nonStopCheckBox, 3, 0, 1, 1)
        self.roundTripRadioButton = QtGui.QRadioButton(self.typeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.roundTripRadioButton.setFont(font)
        self.roundTripRadioButton.setChecked(True)
        self.roundTripRadioButton.setObjectName(_fromUtf8("roundTripRadioButton"))
        self.gridLayout_3.addWidget(self.roundTripRadioButton, 2, 0, 1, 1)
        self.oneWayRadioButton = QtGui.QRadioButton(self.typeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oneWayRadioButton.setFont(font)
        self.oneWayRadioButton.setObjectName(_fromUtf8("oneWayRadioButton"))
        self.gridLayout_3.addWidget(self.oneWayRadioButton, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.typeGroupBox, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.fareWidget, 0, 0, 1, 1)
        self.fareGroupBox = QtGui.QGroupBox(self.dateTimeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fareGroupBox.setFont(font)
        self.fareGroupBox.setObjectName(_fromUtf8("fareGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.fareGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.firstRadioButton = QtGui.QRadioButton(self.fareGroupBox)
        self.firstRadioButton.setChecked(True)
        self.firstRadioButton.setObjectName(_fromUtf8("firstRadioButton"))
        self.verticalLayout.addWidget(self.firstRadioButton)
        self.ecoRadioButton = QtGui.QRadioButton(self.fareGroupBox)
        self.ecoRadioButton.setObjectName(_fromUtf8("ecoRadioButton"))
        self.verticalLayout.addWidget(self.ecoRadioButton)
        self.coachRadioButton = QtGui.QRadioButton(self.fareGroupBox)
        self.coachRadioButton.setObjectName(_fromUtf8("coachRadioButton"))
        self.verticalLayout.addWidget(self.coachRadioButton)
        self.gridLayout_5.addWidget(self.fareGroupBox, 0, 1, 1, 1)
        self.gridLayout_22.addWidget(self.dateTimeGroupBox, 1, 0, 1, 2)
        self.nextWidget = QtGui.QWidget(self.flightInfoTab)
        self.nextWidget.setMaximumSize(QtCore.QSize(16777215, 75))
        self.nextWidget.setObjectName(_fromUtf8("nextWidget"))
        self.verticle_layout6 = QtGui.QVBoxLayout(self.nextWidget)
        self.verticle_layout6.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticle_layout6.setMargin(0)
        self.verticle_layout6.setObjectName(_fromUtf8("verticle_layout6"))
        self.nextCommandLink = QtGui.QCommandLinkButton(self.nextWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(20)
        self.nextCommandLink.setFont(font)
        self.nextCommandLink.setObjectName(_fromUtf8("nextCommandLink"))
        self.verticle_layout6.addWidget(self.nextCommandLink)
        self.gridLayout_22.addWidget(self.nextWidget, 3, 1, 1, 1)
        self.tabWidget.addTab(self.flightInfoTab, _fromUtf8(""))
        self.flightSelectTab = QtGui.QWidget()
        self.flightSelectTab.setObjectName(_fromUtf8("flightSelectTab"))
        self.gridLayout_34 = QtGui.QGridLayout(self.flightSelectTab)
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.departingGroupBox = QtGui.QGroupBox(self.flightSelectTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.departingGroupBox.setFont(font)
        self.departingGroupBox.setObjectName(_fromUtf8("departingGroupBox"))
        self.gridLayout_10 = QtGui.QGridLayout(self.departingGroupBox)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.departingTableWidget = QtGui.QTableWidget(self.departingGroupBox)
        self.departingTableWidget.setObjectName(_fromUtf8("departingTableWidget"))
        self.departingTableWidget.setColumnCount(0)
        self.departingTableWidget.setRowCount(0)
        self.gridLayout_10.addWidget(self.departingTableWidget, 0, 0, 1, 1)
        self.gridLayout_34.addWidget(self.departingGroupBox, 0, 0, 1, 1)
        self.returnGroupBox = QtGui.QGroupBox(self.flightSelectTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.returnGroupBox.setFont(font)
        self.returnGroupBox.setObjectName(_fromUtf8("returnGroupBox"))
        self.gridLayout_37 = QtGui.QGridLayout(self.returnGroupBox)
        self.gridLayout_37.setObjectName(_fromUtf8("gridLayout_37"))
        self.returnTableWidget = QtGui.QTableWidget(self.returnGroupBox)
        self.returnTableWidget.setObjectName(_fromUtf8("returnTableWidget"))
        self.returnTableWidget.setColumnCount(0)
        self.returnTableWidget.setRowCount(0)
        self.gridLayout_37.addWidget(self.returnTableWidget, 0, 0, 1, 1)
        self.gridLayout_34.addWidget(self.returnGroupBox, 1, 0, 1, 1)
        self.nextWidget_2 = QtGui.QWidget(self.flightSelectTab)
        self.nextWidget_2.setMaximumSize(QtCore.QSize(16777215, 75))
        self.nextWidget_2.setObjectName(_fromUtf8("nextWidget_2"))
        self.gridLayout_11 = QtGui.QGridLayout(self.nextWidget_2)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.nextCommandLink_2 = QtGui.QCommandLinkButton(self.nextWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(20)
        self.nextCommandLink_2.setFont(font)
        self.nextCommandLink_2.setIconSize(QtCore.QSize(20, 20))
        self.nextCommandLink_2.setObjectName(_fromUtf8("nextCommandLink_2"))
        self.gridLayout_11.addWidget(self.nextCommandLink_2, 0, 0, 1, 1)
        self.gridLayout_34.addWidget(self.nextWidget_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.flightSelectTab, _fromUtf8(""))
        self.passInfoTab = QtGui.QWidget()
        self.passInfoTab.setObjectName(_fromUtf8("passInfoTab"))
        self.gridLayout_36 = QtGui.QGridLayout(self.passInfoTab)
        self.gridLayout_36.setObjectName(_fromUtf8("gridLayout_36"))
        self.stackedWidget = QtGui.QStackedWidget(self.passInfoTab)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        """self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackedWidget.addWidget(self.page_2)"""
        self.gridLayout_36.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.passInfoTab, _fromUtf8(""))
        self.paymentTab = QtGui.QWidget()
        self.paymentTab.setObjectName(_fromUtf8("paymentTab"))
        self.gridLayout_38 = QtGui.QGridLayout(self.paymentTab)
        self.gridLayout_38.setObjectName(_fromUtf8("gridLayout_38"))
        self.costGroupBox = QtGui.QGroupBox(self.paymentTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.costGroupBox.setFont(font)
        self.costGroupBox.setObjectName(_fromUtf8("costGroupBox"))
        self.gridLayout_12 = QtGui.QGridLayout(self.costGroupBox)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.departingTableWidget_2 = QtGui.QTableWidget(self.costGroupBox)
        self.departingTableWidget_2.setObjectName(_fromUtf8("departingTableWidget_2"))
        self.departingTableWidget_2.setColumnCount(0)
        self.departingTableWidget_2.setRowCount(0)
        self.gridLayout_12.addWidget(self.departingTableWidget_2, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.costGroupBox, 0, 0, 1, 1)
        self.creditGroupBox = QtGui.QGroupBox(self.paymentTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.creditGroupBox.setFont(font)
        self.creditGroupBox.setObjectName(_fromUtf8("creditGroupBox"))
        self.gridLayout_13 = QtGui.QGridLayout(self.creditGroupBox)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.visaRadioButton = QtGui.QRadioButton(self.creditGroupBox)
        self.visaRadioButton.setObjectName(_fromUtf8("visaRadioButton"))
        self.gridLayout_13.addWidget(self.visaRadioButton, 0, 0, 1, 1)
        self.amexRadioButton = QtGui.QRadioButton(self.creditGroupBox)
        self.amexRadioButton.setObjectName(_fromUtf8("amexRadioButton"))
        self.gridLayout_13.addWidget(self.amexRadioButton, 0, 4, 1, 1)
        self.creditNameLabel = QtGui.QLabel(self.creditGroupBox)
        self.creditNameLabel.setObjectName(_fromUtf8("creditNameLabel"))
        self.gridLayout_13.addWidget(self.creditNameLabel, 1, 0, 1, 1)
        self.creditNameLineEdit = QtGui.QLineEdit(self.creditGroupBox)
        self.creditNameLineEdit.setObjectName(_fromUtf8("creditNameLineEdit"))
        self.gridLayout_13.addWidget(self.creditNameLineEdit, 1, 2, 1, 3)
        self.cardNumberLabel = QtGui.QLabel(self.creditGroupBox)
        self.cardNumberLabel.setObjectName(_fromUtf8("cardNumberLabel"))
        self.gridLayout_13.addWidget(self.cardNumberLabel, 2, 0, 1, 1)
        self.cardNumberLineEdit = QtGui.QLineEdit(self.creditGroupBox)
        self.cardNumberLineEdit.setObjectName(_fromUtf8("cardNumberLineEdit"))
        self.gridLayout_13.addWidget(self.cardNumberLineEdit, 2, 2, 1, 3)
        self.cvvLabel = QtGui.QLabel(self.creditGroupBox)
        self.cvvLabel.setObjectName(_fromUtf8("cvvLabel"))
        self.gridLayout_13.addWidget(self.cvvLabel, 4, 0, 1, 1)
        self.expLabel = QtGui.QLabel(self.creditGroupBox)
        self.expLabel.setObjectName(_fromUtf8("expLabel"))
        self.gridLayout_13.addWidget(self.expLabel, 4, 3, 1, 1)
        self.creditDateEdit = QtGui.QDateEdit(self.creditGroupBox)
        self.creditDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 3, 1), QtCore.QTime(0, 0, 0)))
        self.creditDateEdit.setCalendarPopup(True)
        self.creditDateEdit.setObjectName(_fromUtf8("creditDateEdit"))
        self.gridLayout_13.addWidget(self.creditDateEdit, 4, 4, 1, 1)
        self.cvvLineEdit = QtGui.QLineEdit(self.creditGroupBox)
        self.cvvLineEdit.setObjectName(_fromUtf8("cvvLineEdit"))
        self.gridLayout_13.addWidget(self.cvvLineEdit, 4, 2, 1, 1)
        self.mcRadioButton = QtGui.QRadioButton(self.creditGroupBox)
        self.mcRadioButton.setObjectName(_fromUtf8("mcRadioButton"))
        self.gridLayout_13.addWidget(self.mcRadioButton, 0, 2, 1, 1)
        self.gridLayout_38.addWidget(self.creditGroupBox, 1, 0, 1, 1)
        self.cancelPurchaseWidget = QtGui.QWidget(self.paymentTab)
        self.cancelPurchaseWidget.setMinimumSize(QtCore.QSize(0, 75))
        self.cancelPurchaseWidget.setObjectName(_fromUtf8("cancelPurchaseWidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.cancelPurchaseWidget)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.cancelButton = QtGui.QPushButton(self.cancelPurchaseWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.gridLayout_8.addWidget(self.cancelButton, 0, 0, 1, 1)
        self.purchaseButton = QtGui.QPushButton(self.cancelPurchaseWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.purchaseButton.setFont(font)
        self.purchaseButton.setObjectName(_fromUtf8("purchaseButton"))
        self.gridLayout_8.addWidget(self.purchaseButton, 0, 1, 1, 1)
        self.gridLayout_38.addWidget(self.cancelPurchaseWidget, 2, 0, 1, 1)
        self.tabWidget.addTab(self.paymentTab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRes = QtGui.QMenu(self.menubar)
        self.menuRes.setObjectName(_fromUtf8("menuRes"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionNewRes = QtGui.QAction(MainWindow)
        self.actionNewRes.setObjectName(_fromUtf8("actionNewRes"))
        self.actionCancelRes = QtGui.QAction(MainWindow)
        self.actionCancelRes.setObjectName(_fromUtf8("actionCancelRes"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuRes.addAction(self.actionNewRes)
        self.menuRes.addAction(self.actionCancelRes)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRes.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Fly Right Airlines", None))
        self.gridGroupBox.setTitle(_translate("MainWindow", "Existing Reservation", None))
        self.lookupButton.setText(_translate("MainWindow", "Lookup", None))
        self.label_3.setText(_translate("MainWindow", "         Zip Code                   ", None))
        self.lookupButton_2.setText(_translate("MainWindow", "Lookup", None))
        self.label_2.setText(_translate("MainWindow", "Last Name", None))
        self.label_4.setText(_translate("MainWindow", "Reservation #", None))
        self.label.setText(_translate("MainWindow", "First Name", None))
        self.label_5.setText(_translate("MainWindow", " OR", None))
        self.nextCommandLink_3.setText(_translate("MainWindow", "New Reservation", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600; color:#021b41;\">Fly Right Airlines</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lookupTab), _translate("MainWindow", "Lookup", None))
        self.destGroupBox.setTitle(_translate("MainWindow", "Destination", None))
        self.fromLabel.setText(_translate("MainWindow", "From:", None))
        self.fromComboBox.setItemText(1, _translate("MainWindow", "Dallas, Texas (DFW)", None))
        self.fromComboBox.setItemText(2, _translate("MainWindow", "Denver, Colorado (DEN)", None))
        self.fromComboBox.setItemText(3, _translate("MainWindow", "Las Vegas, Nevada (LAS)", None))
        self.fromComboBox.setItemText(4, _translate("MainWindow", "Los Angeles, California (LAX)", None))
        self.fromComboBox.setItemText(5, _translate("MainWindow", "Miami, Florida (MIA)", None))
        self.fromComboBox.setItemText(6, _translate("MainWindow", "New York, New York (JFK)", None))
        self.fromComboBox.setItemText(7, _translate("MainWindow", "San Francisco, California (SFO)", None))
        self.toLabel.setText(_translate("MainWindow", "To:", None))
        self.toComboBox.setItemText(1, _translate("MainWindow", "Dallas, Texas (DFW)", None))
        self.toComboBox.setItemText(2, _translate("MainWindow", "Denver, Colorado (DEN)", None))
        self.toComboBox.setItemText(3, _translate("MainWindow", "Las Vegas, Nevada (LAS)", None))
        self.toComboBox.setItemText(4, _translate("MainWindow", "Los Angeles, California (LAX)", None))
        self.toComboBox.setItemText(5, _translate("MainWindow", "Miami, Florida (MIA)", None))
        self.toComboBox.setItemText(6, _translate("MainWindow", "San Francisco, California (SFO)", None))
        self.passGroupBox.setTitle(_translate("MainWindow", "Number of Passengers", None))
        self.passComboBox.setItemText(1, _translate("MainWindow", "1", None))
        self.passComboBox.setItemText(2, _translate("MainWindow", "2", None))
        self.passComboBox.setItemText(3, _translate("MainWindow", "3", None))
        self.passComboBox.setItemText(4, _translate("MainWindow", "4", None))
        self.passComboBox.setItemText(5, _translate("MainWindow", "5", None))
        self.passComboBox.setItemText(6, _translate("MainWindow", "6", None))
        self.passComboBox.setItemText(7, _translate("MainWindow", "7", None))
        self.passComboBox.setItemText(8, _translate("MainWindow", "8", None))
        self.dateTimeGroupBox.setTitle(_translate("MainWindow", "Date / Time", None))
        self.departDateLabel.setText(_translate("MainWindow", "Departure Date:", None))
        self.retDateLabel.setText(_translate("MainWindow", "Return Date:", None))
        self.departTimeLabel.setText(_translate("MainWindow", "Time:", None))
        self.returnTimeLabel.setText(_translate("MainWindow", "Time:", None))
        self.typeGroupBox.setTitle(_translate("MainWindow", "Type of Flight", None))
        self.nonStopCheckBox.setText(_translate("MainWindow", "Non Stop Flights", None))
        self.roundTripRadioButton.setText(_translate("MainWindow", "Round Trip", None))
        self.oneWayRadioButton.setText(_translate("MainWindow", "One Way", None))
        self.fareGroupBox.setTitle(_translate("MainWindow", "Fare Class", None))
        self.firstRadioButton.setText(_translate("MainWindow", "First Class", None))
        self.ecoRadioButton.setText(_translate("MainWindow", "Economy Plus", None))
        self.coachRadioButton.setText(_translate("MainWindow", "Coach", None))
        self.nextCommandLink.setText(_translate("MainWindow", "Next", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flightInfoTab), _translate("MainWindow", "Flight Info", None))
        self.departingGroupBox.setTitle(_translate("MainWindow", "Departing Flights", None))
        self.returnGroupBox.setTitle(_translate("MainWindow", "Return Flights", None))
        self.nextCommandLink_2.setText(_translate("MainWindow", "Next", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flightSelectTab), _translate("MainWindow", "Flight Selection", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.passInfoTab), _translate("MainWindow", "Passenger Info", None))
        self.costGroupBox.setTitle(_translate("MainWindow", "Cost", None))
        self.creditGroupBox.setTitle(_translate("MainWindow", "Credit Card", None))
        self.visaRadioButton.setText(_translate("MainWindow", "Visa", None))
        self.amexRadioButton.setText(_translate("MainWindow", "American Express", None))
        self.creditNameLabel.setText(_translate("MainWindow", "Name on card:", None))
        self.cardNumberLabel.setText(_translate("MainWindow", "Card Number:", None))
        self.cvvLabel.setText(_translate("MainWindow", "CVV Number:", None))
        self.expLabel.setText(_translate("MainWindow", "Expires:", None))
        self.mcRadioButton.setText(_translate("MainWindow", "MasterCard", None))
        self.cancelButton.setText(_translate("MainWindow", "Cancel", None))
        self.purchaseButton.setText(_translate("MainWindow", "Purchase", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.paymentTab), _translate("MainWindow", "Payment", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuRes.setTitle(_translate("MainWindow", "Reservation", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionNew.setText(_translate("MainWindow", "New Reservation", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))
        self.actionNewRes.setText(_translate("MainWindow", "New", None))
        self.actionCancelRes.setText(_translate("MainWindow", "Cancel", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As...", None))
        self.actionPrint.setText(_translate("MainWindow", "Print", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

import res
