# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FlyRightAirlines1-5.ui'
#
# Created: Sun Feb 22 19:11:40 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(674, 673)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("air_plane_airport.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.lookupTab = QtGui.QWidget()
        self.lookupTab.setObjectName(_fromUtf8("lookupTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.lookupTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.flyRightBannerLabel = QtGui.QLabel(self.lookupTab)
        self.flyRightBannerLabel.setMaximumSize(QtCore.QSize(16777215, 75))
        self.flyRightBannerLabel.setObjectName(_fromUtf8("flyRightBannerLabel"))
        self.verticalLayout_7.addWidget(self.flyRightBannerLabel)
        self.bannerImageWidget = QtGui.QWidget(self.lookupTab)
        self.bannerImageWidget.setMinimumSize(QtCore.QSize(0, 250))
        self.bannerImageWidget.setObjectName(_fromUtf8("bannerImageWidget"))
        self.gridLayout_23 = QtGui.QGridLayout(self.bannerImageWidget)
        self.gridLayout_23.setMargin(0)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.bannerImageLabel = QtGui.QLabel(self.bannerImageWidget)
        self.bannerImageLabel.setText(_fromUtf8(""))
        self.bannerImageLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/airplane.png")))
        self.bannerImageLabel.setObjectName(_fromUtf8("bannerImageLabel"))
        self.gridLayout_23.addWidget(self.bannerImageLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addWidget(self.bannerImageWidget)
        self.existingGroupBox = QtGui.QGroupBox(self.lookupTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.existingGroupBox.setFont(font)
        self.existingGroupBox.setObjectName(_fromUtf8("existingGroupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.existingGroupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lastNameLineEdit = QtGui.QLineEdit(self.existingGroupBox)
        self.lastNameLineEdit.setObjectName(_fromUtf8("lastNameLineEdit"))
        self.gridLayout_9.addWidget(self.lastNameLineEdit, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.lastNameLabel = QtGui.QLabel(self.existingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lastNameLabel.setFont(font)
        self.lastNameLabel.setObjectName(_fromUtf8("lastNameLabel"))
        self.gridLayout_9.addWidget(self.lastNameLabel, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lookupButton = QtGui.QPushButton(self.existingGroupBox)
        self.lookupButton.setObjectName(_fromUtf8("lookupButton"))
        self.gridLayout_9.addWidget(self.lookupButton, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.resNumLineEdit = QtGui.QLineEdit(self.existingGroupBox)
        self.resNumLineEdit.setObjectName(_fromUtf8("resNumLineEdit"))
        self.gridLayout_9.addWidget(self.resNumLineEdit, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.resNumLabel = QtGui.QLabel(self.existingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resNumLabel.setFont(font)
        self.resNumLabel.setObjectName(_fromUtf8("resNumLabel"))
        self.gridLayout_9.addWidget(self.resNumLabel, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.firstNameLineEdit = QtGui.QLineEdit(self.existingGroupBox)
        self.firstNameLineEdit.setObjectName(_fromUtf8("firstNameLineEdit"))
        self.gridLayout_9.addWidget(self.firstNameLineEdit, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.firstNameLabel = QtGui.QLabel(self.existingGroupBox)
        self.firstNameLabel.setObjectName(_fromUtf8("firstNameLabel"))
        self.gridLayout_9.addWidget(self.firstNameLabel, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.verticalLayout_7.addWidget(self.existingGroupBox)
        self.newResWidget = QtGui.QWidget(self.lookupTab)
        self.newResWidget.setMaximumSize(QtCore.QSize(16777215, 75))
        self.newResWidget.setObjectName(_fromUtf8("newResWidget"))
        self.gridLayout_20 = QtGui.QGridLayout(self.newResWidget)
        self.gridLayout_20.setMargin(0)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.newResCommandLink = QtGui.QCommandLinkButton(self.newResWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(16)
        self.newResCommandLink.setFont(font)
        self.newResCommandLink.setObjectName(_fromUtf8("newResCommandLink"))
        self.gridLayout_20.addWidget(self.newResCommandLink, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.verticalLayout_7.addWidget(self.newResWidget)
        self.tabWidget.addTab(self.lookupTab, _fromUtf8(""))
        self.flightInfoTab = QtGui.QWidget()
        self.flightInfoTab.setObjectName(_fromUtf8("flightInfoTab"))
        self.gridLayout_22 = QtGui.QGridLayout(self.flightInfoTab)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.destGroupBox = QtGui.QGroupBox(self.flightInfoTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.destGroupBox.setFont(font)
        self.destGroupBox.setObjectName(_fromUtf8("destGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.destGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.fromLabel = QtGui.QLabel(self.destGroupBox)
        self.fromLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fromLabel.setFont(font)
        self.fromLabel.setObjectName(_fromUtf8("fromLabel"))
        self.gridLayout_4.addWidget(self.fromLabel, 0, 0, 1, 1)
        self.fromComboBox = QtGui.QComboBox(self.destGroupBox)
        self.fromComboBox.setObjectName(_fromUtf8("fromComboBox"))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.fromComboBox.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.fromComboBox, 0, 1, 1, 1)
        self.toLabel = QtGui.QLabel(self.destGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.toLabel.setFont(font)
        self.toLabel.setObjectName(_fromUtf8("toLabel"))
        self.gridLayout_4.addWidget(self.toLabel, 1, 0, 1, 1)
        self.toComboBox = QtGui.QComboBox(self.destGroupBox)
        self.toComboBox.setObjectName(_fromUtf8("toComboBox"))
        self.toComboBox.addItem(_fromUtf8(""))
        self.toComboBox.addItem(_fromUtf8(""))
        self.toComboBox.addItem(_fromUtf8(""))
        self.toComboBox.addItem(_fromUtf8(""))
        self.toComboBox.addItem(_fromUtf8(""))
        self.toComboBox.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.toComboBox, 1, 1, 1, 1)
        self.gridLayout_22.addWidget(self.destGroupBox, 0, 0, 1, 1)
        self.passGroupBox = QtGui.QGroupBox(self.flightInfoTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.passGroupBox.setFont(font)
        self.passGroupBox.setObjectName(_fromUtf8("passGroupBox"))
        self.gridLayout_35 = QtGui.QGridLayout(self.passGroupBox)
        self.gridLayout_35.setObjectName(_fromUtf8("gridLayout_35"))
        self.passComboBox = QtGui.QComboBox(self.passGroupBox)
        self.passComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.passComboBox.setObjectName(_fromUtf8("passComboBox"))
        self.passComboBox.insertItems(0, [str(i) for i in range (1,9)])
        self.gridLayout_35.addWidget(self.passComboBox, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.passGroupBox, 0, 1, 1, 1)
        self.dateTimeGroupBox = QtGui.QGroupBox(self.flightInfoTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dateTimeGroupBox.setFont(font)
        self.dateTimeGroupBox.setObjectName(_fromUtf8("dateTimeGroupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dateTimeGroupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.departDateLabel = QtGui.QLabel(self.dateTimeGroupBox)
        self.departDateLabel.setObjectName(_fromUtf8("departDateLabel"))
        self.gridLayout_5.addWidget(self.departDateLabel, 0, 0, 1, 1)
        self.retDateLabel = QtGui.QLabel(self.dateTimeGroupBox)
        self.retDateLabel.setObjectName(_fromUtf8("retDateLabel"))
        self.gridLayout_5.addWidget(self.retDateLabel, 3, 0, 1, 1)
        self.retDateEdit = QtGui.QDateEdit(self.dateTimeGroupBox)
        self.retDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 3, 1), QtCore.QTime(0, 0, 0)))
        self.retDateEdit.setCalendarPopup(True)
        self.retDateEdit.setObjectName(_fromUtf8("retDateEdit"))
        self.gridLayout_5.addWidget(self.retDateEdit, 4, 0, 1, 1)
        self.departDateEdit = QtGui.QDateEdit(self.dateTimeGroupBox)
        self.departDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 3, 1), QtCore.QTime(0, 0, 0)))
        self.departDateEdit.setTime(QtCore.QTime(0, 0, 0))
        self.departDateEdit.setCalendarPopup(True)
        self.departDateEdit.setObjectName(_fromUtf8("departDateEdit"))
        self.gridLayout_5.addWidget(self.departDateEdit, 1, 0, 1, 1)
        self.departTimeLabel = QtGui.QLabel(self.dateTimeGroupBox)
        self.departTimeLabel.setObjectName(_fromUtf8("departTimeLabel"))
        self.gridLayout_5.addWidget(self.departTimeLabel, 0, 1, 1, 1)
        self.departTimeEdit = QtGui.QTimeEdit(self.dateTimeGroupBox)
        self.departTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(12, 0, 0)))
        self.departTimeEdit.setCalendarPopup(True)
        self.departTimeEdit.setObjectName(_fromUtf8("departTimeEdit"))
        self.gridLayout_5.addWidget(self.departTimeEdit, 1, 1, 1, 1)
        self.returnTimeLabel = QtGui.QLabel(self.dateTimeGroupBox)
        self.returnTimeLabel.setObjectName(_fromUtf8("returnTimeLabel"))
        self.gridLayout_5.addWidget(self.returnTimeLabel, 3, 1, 1, 1)
        self.retTimeEdit = QtGui.QTimeEdit(self.dateTimeGroupBox)
        self.retTimeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(12, 0, 0)))
        self.retTimeEdit.setCalendarPopup(True)
        self.retTimeEdit.setObjectName(_fromUtf8("retTimeEdit"))
        self.gridLayout_5.addWidget(self.retTimeEdit, 4, 1, 1, 1)
        self.gridLayout_22.addWidget(self.dateTimeGroupBox, 1, 0, 1, 2)
        self.fareWidget = QtGui.QWidget(self.flightInfoTab)
        self.fareWidget.setObjectName(_fromUtf8("fareWidget"))
        self.gridLayout = QtGui.QGridLayout(self.fareWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fareGroupBox = QtGui.QGroupBox(self.fareWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fareGroupBox.setFont(font)
        self.fareGroupBox.setObjectName(_fromUtf8("fareGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.fareGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.firstRadioButton = QtGui.QRadioButton(self.fareGroupBox)
        self.firstRadioButton.setChecked(True)
        self.firstRadioButton.setObjectName(_fromUtf8("firstRadioButton"))
        self.verticalLayout.addWidget(self.firstRadioButton)
        self.ecoRadioButton = QtGui.QRadioButton(self.fareGroupBox)
        self.ecoRadioButton.setObjectName(_fromUtf8("ecoRadioButton"))
        self.verticalLayout.addWidget(self.ecoRadioButton)
        self.coachRadioButton = QtGui.QRadioButton(self.fareGroupBox)
        self.coachRadioButton.setObjectName(_fromUtf8("coachRadioButton"))
        self.verticalLayout.addWidget(self.coachRadioButton)
        self.gridLayout.addWidget(self.fareGroupBox, 0, 0, 1, 1)
        self.typeGroupBox = QtGui.QGroupBox(self.fareWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.typeGroupBox.setFont(font)
        self.typeGroupBox.setObjectName(_fromUtf8("typeGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.typeGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.nonStopRadioButton = QtGui.QCheckBox(self.typeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nonStopRadioButton.setFont(font)
        self.nonStopRadioButton.setObjectName(_fromUtf8("nonStopRadioButton"))
        self.gridLayout_3.addWidget(self.nonStopRadioButton, 3, 0, 1, 1)
        self.roundTripRadioButton = QtGui.QRadioButton(self.typeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.roundTripRadioButton.setFont(font)
        self.roundTripRadioButton.setChecked(True)
        self.roundTripRadioButton.setObjectName(_fromUtf8("roundTripRadioButton"))
        self.gridLayout_3.addWidget(self.roundTripRadioButton, 2, 0, 1, 1)
        self.oneWayRadioButton = QtGui.QRadioButton(self.typeGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oneWayRadioButton.setFont(font)
        self.oneWayRadioButton.setObjectName(_fromUtf8("oneWayRadioButton"))
        self.gridLayout_3.addWidget(self.oneWayRadioButton, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.typeGroupBox, 0, 1, 1, 1)
        self.gridLayout_22.addWidget(self.fareWidget, 2, 0, 1, 2)
        self.nextWidget = QtGui.QWidget(self.flightInfoTab)
        self.nextWidget.setMaximumSize(QtCore.QSize(16777215, 75))
        self.nextWidget.setObjectName(_fromUtf8("nextWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.nextWidget)
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.nextCommandLink = QtGui.QCommandLinkButton(self.nextWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(20)
        self.nextCommandLink.setFont(font)
        self.nextCommandLink.setObjectName(_fromUtf8("nextCommandLink"))
        self.verticalLayout_6.addWidget(self.nextCommandLink, QtCore.Qt.AlignRight)
        self.gridLayout_22.addWidget(self.nextWidget, 3, 1, 1, 1)
        self.tabWidget.addTab(self.flightInfoTab, _fromUtf8(""))
        self.flightSelectTab = QtGui.QWidget()
        self.flightSelectTab.setObjectName(_fromUtf8("flightSelectTab"))
        self.gridLayout_34 = QtGui.QGridLayout(self.flightSelectTab)
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.departingGroupBox = QtGui.QGroupBox(self.flightSelectTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.departingGroupBox.setFont(font)
        self.departingGroupBox.setObjectName(_fromUtf8("departingGroupBox"))
        self.gridLayout_10 = QtGui.QGridLayout(self.departingGroupBox)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.departingTableView = QtGui.QTableView(self.departingGroupBox)
        self.departingTableView.setObjectName(_fromUtf8("departingTableView"))
        self.gridLayout_10.addWidget(self.departingTableView, 0, 0, 1, 1)
        self.gridLayout_34.addWidget(self.departingGroupBox, 0, 0, 1, 1)
        self.returnGroupBox = QtGui.QGroupBox(self.flightSelectTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.returnGroupBox.setFont(font)
        self.returnGroupBox.setObjectName(_fromUtf8("returnGroupBox"))
        self.gridLayout_37 = QtGui.QGridLayout(self.returnGroupBox)
        self.gridLayout_37.setObjectName(_fromUtf8("gridLayout_37"))
        self.returnTableView = QtGui.QTableView(self.returnGroupBox)
        self.returnTableView.setObjectName(_fromUtf8("returnTableView"))
        self.gridLayout_37.addWidget(self.returnTableView, 0, 0, 1, 1)
        self.gridLayout_34.addWidget(self.returnGroupBox, 1, 0, 1, 1)
        self.nextWidget_2 = QtGui.QWidget(self.flightSelectTab)
        self.nextWidget_2.setMaximumSize(QtCore.QSize(16777215, 75))
        self.nextWidget_2.setObjectName(_fromUtf8("nextWidget_2"))
        self.gridLayout_11 = QtGui.QGridLayout(self.nextWidget_2)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.nextCommandLink_2 = QtGui.QCommandLinkButton(self.nextWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(20)
        self.nextCommandLink_2.setFont(font)
        self.nextCommandLink_2.setIconSize(QtCore.QSize(20, 20))
        self.nextCommandLink_2.setObjectName(_fromUtf8("nextCommandLink_2"))
        self.gridLayout_11.addWidget(self.nextCommandLink_2, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_34.addWidget(self.nextWidget_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.flightSelectTab, _fromUtf8(""))
        self.passInfoTab = QtGui.QWidget()
        self.passInfoTab.setObjectName(_fromUtf8("passInfoTab"))
        self.gridLayout_36 = QtGui.QGridLayout(self.passInfoTab)
        self.gridLayout_36.setObjectName(_fromUtf8("gridLayout_36"))
        #start stackedWidget
        
        self.stackedWidget = QtGui.QStackedWidget(self.passInfoTab)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        #start passPage
        
        """self.passPage = QtGui.QWidget()
        self.passPage.setObjectName(_fromUtf8("passPage"))
        self.gridLayout_16 = QtGui.QGridLayout(self.passPage)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.fwdBackNavWidget = QtGui.QWidget(self.passPage)
        self.fwdBackNavWidget.setMaximumSize(QtCore.QSize(50, 50))
        self.fwdBackNavWidget.setObjectName(_fromUtf8("fwdBackNavWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.fwdBackNavWidget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.backStackNavButton = QtGui.QPushButton(self.fwdBackNavWidget)
        self.backStackNavButton.setObjectName(_fromUtf8("backStackNavButton"))
        self.horizontalLayout_2.addWidget(self.backStackNavButton)
        self.fwdStackNavButton = QtGui.QPushButton(self.fwdBackNavWidget)
        self.fwdStackNavButton.setObjectName(_fromUtf8("fwdStackNavButton"))
        self.horizontalLayout_2.addWidget(self.fwdStackNavButton)
        self.gridLayout_16.addWidget(self.fwdBackNavWidget, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.passengerGroupBox = QtGui.QGroupBox(self.passPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.passengerGroupBox.setFont(font)
        self.passengerGroupBox.setObjectName(_fromUtf8("passengerGroupBox"))
        self.gridLayout_12 = QtGui.QGridLayout(self.passengerGroupBox)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.seatGroupBox = QtGui.QGroupBox(self.passengerGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.seatGroupBox.setFont(font)
        self.seatGroupBox.setObjectName(_fromUtf8("seatGroupBox"))
        self.gridLayout_21 = QtGui.QGridLayout(self.seatGroupBox)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.windowRadioButton = QtGui.QRadioButton(self.seatGroupBox)
        self.windowRadioButton.setObjectName(_fromUtf8("windowRadioButton"))
        self.gridLayout_21.addWidget(self.windowRadioButton, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.aisleRadioButton = QtGui.QRadioButton(self.seatGroupBox)
        self.aisleRadioButton.setObjectName(_fromUtf8("aisleRadioButton"))
        self.gridLayout_21.addWidget(self.aisleRadioButton, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.centerRadioButton = QtGui.QRadioButton(self.seatGroupBox)
        self.centerRadioButton.setObjectName(_fromUtf8("centerRadioButton"))
        self.gridLayout_21.addWidget(self.centerRadioButton, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_12.addWidget(self.seatGroupBox, 0, 2, 2, 1)
        self.bagGroupBox = QtGui.QGroupBox(self.passengerGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bagGroupBox.setFont(font)
        self.bagGroupBox.setObjectName(_fromUtf8("bagGroupBox"))
        self.gridLayout_46 = QtGui.QGridLayout(self.bagGroupBox)
        self.gridLayout_46.setObjectName(_fromUtf8("gridLayout_46"))
        self.bagSpinBox = QtGui.QSpinBox(self.bagGroupBox)
        self.bagSpinBox.setObjectName(_fromUtf8("bagSpinBox"))
        self.gridLayout_46.addWidget(self.bagSpinBox, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_12.addWidget(self.bagGroupBox, 2, 2, 2, 1)
        self.specialGroupBox = QtGui.QGroupBox(self.passengerGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.specialGroupBox.setFont(font)
        self.specialGroupBox.setObjectName(_fromUtf8("specialGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.specialGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.handiCheckBox = QtGui.QCheckBox(self.specialGroupBox)
        self.handiCheckBox.setObjectName(_fromUtf8("handiCheckBox"))
        self.verticalLayout_2.addWidget(self.handiCheckBox)
        self.mealCheckBox = QtGui.QCheckBox(self.specialGroupBox)
        self.mealCheckBox.setObjectName(_fromUtf8("mealCheckBox"))
        self.verticalLayout_2.addWidget(self.mealCheckBox)
        self.commentsLabel = QtGui.QLabel(self.specialGroupBox)
        self.commentsLabel.setObjectName(_fromUtf8("commentsLabel"))
        self.verticalLayout_2.addWidget(self.commentsLabel)
        self.commentsTextEdit = QtGui.QTextEdit(self.specialGroupBox)
        self.commentsTextEdit.setObjectName(_fromUtf8("commentsTextEdit"))
        self.verticalLayout_2.addWidget(self.commentsTextEdit)
        self.gridLayout_12.addWidget(self.specialGroupBox, 4, 2, 2, 1)
        self.NameAddressGroupBox = QtGui.QGroupBox(self.passengerGroupBox)
        self.NameAddressGroupBox.setObjectName(_fromUtf8("NameAddressGroupBox"))
        self.gridLayout_19 = QtGui.QGridLayout(self.NameAddressGroupBox)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.passFirstLabel = QtGui.QLabel(self.NameAddressGroupBox)
        self.passFirstLabel.setObjectName(_fromUtf8("passFirstLabel"))
        self.gridLayout_19.addWidget(self.passFirstLabel, 1, 0, 1, 1)
        self.passAddressLineEdit = QtGui.QLineEdit(self.NameAddressGroupBox)
        self.passAddressLineEdit.setObjectName(_fromUtf8("passAddressLineEdit"))
        self.gridLayout_19.addWidget(self.passAddressLineEdit, 4, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.passCityLabel = QtGui.QLabel(self.NameAddressGroupBox)
        self.passCityLabel.setObjectName(_fromUtf8("passCityLabel"))
        self.gridLayout_19.addWidget(self.passCityLabel, 5, 0, 1, 1)
        self.passAddressLabel = QtGui.QLabel(self.NameAddressGroupBox)
        self.passAddressLabel.setObjectName(_fromUtf8("passAddressLabel"))
        self.gridLayout_19.addWidget(self.passAddressLabel, 4, 0, 1, 1)
        self.passFirstLineEdit = QtGui.QLineEdit(self.NameAddressGroupBox)
        self.passFirstLineEdit.setObjectName(_fromUtf8("passFirstLineEdit"))
        self.gridLayout_19.addWidget(self.passFirstLineEdit, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.passMidLabel = QtGui.QLabel(self.NameAddressGroupBox)
        self.passMidLabel.setObjectName(_fromUtf8("passMidLabel"))
        self.gridLayout_19.addWidget(self.passMidLabel, 2, 0, 1, 1)
        self.passMidLineEdit = QtGui.QLineEdit(self.NameAddressGroupBox)
        self.passMidLineEdit.setObjectName(_fromUtf8("passMidLineEdit"))
        self.gridLayout_19.addWidget(self.passMidLineEdit, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.passLastLabel = QtGui.QLabel(self.NameAddressGroupBox)
        self.passLastLabel.setObjectName(_fromUtf8("passLastLabel"))
        self.gridLayout_19.addWidget(self.passLastLabel, 3, 0, 1, 1)
        self.PassLastLineEdit = QtGui.QLineEdit(self.NameAddressGroupBox)
        self.PassLastLineEdit.setObjectName(_fromUtf8("PassLastLineEdit"))
        self.gridLayout_19.addWidget(self.PassLastLineEdit, 3, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.passCityLineEdit = QtGui.QLineEdit(self.NameAddressGroupBox)
        self.passCityLineEdit.setObjectName(_fromUtf8("passCityLineEdit"))
        self.gridLayout_19.addWidget(self.passCityLineEdit, 5, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.passStateLabel = QtGui.QLabel(self.NameAddressGroupBox)
        self.passStateLabel.setObjectName(_fromUtf8("passStateLabel"))
        self.gridLayout_19.addWidget(self.passStateLabel, 6, 0, 1, 1)
        self.passStateComboBox = QtGui.QComboBox(self.NameAddressGroupBox)
        self.passStateComboBox.setObjectName(_fromUtf8("passStateComboBox"))
        states=['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']
        self.passStateComboBox.insertItems (0, states)
        self.gridLayout_19.addWidget(self.passStateComboBox, 6, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.passZipLabel = QtGui.QLabel(self.NameAddressGroupBox)
        self.passZipLabel.setObjectName(_fromUtf8("passZipLabel"))
        self.gridLayout_19.addWidget(self.passZipLabel, 7, 0, 1, 1)
        self.passZipLineEdit = QtGui.QLineEdit(self.NameAddressGroupBox)
        self.passZipLineEdit.setObjectName(_fromUtf8("passZipLineEdit"))
        self.gridLayout_19.addWidget(self.passZipLineEdit, 7, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.mrAlignWidget = QtGui.QWidget(self.NameAddressGroupBox)
        self.mrAlignWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.mrAlignWidget.setObjectName(_fromUtf8("mrAlignWidget"))
        self.gridLayout_18 = QtGui.QGridLayout(self.mrAlignWidget)
        self.gridLayout_18.setMargin(0)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.mrsRadioButton = QtGui.QRadioButton(self.mrAlignWidget)
        self.mrsRadioButton.setObjectName(_fromUtf8("mrsRadioButton"))
        self.gridLayout_18.addWidget(self.mrsRadioButton, 0, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.mrRadioButton = QtGui.QRadioButton(self.mrAlignWidget)
        self.mrRadioButton.setObjectName(_fromUtf8("mrRadioButton"))
        self.gridLayout_18.addWidget(self.mrRadioButton, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.msRadioButton = QtGui.QRadioButton(self.mrAlignWidget)
        self.msRadioButton.setObjectName(_fromUtf8("msRadioButton"))
        self.gridLayout_18.addWidget(self.msRadioButton, 0, 3, 1, 1)
        self.gridLayout_19.addWidget(self.mrAlignWidget, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.NameAddressGroupBox, 0, 0, 6, 1)
        self.gridLayout_16.addWidget(self.passengerGroupBox, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.passPage)"""
        #end stackedWidget
        """
        self.gridLayout_36.addWidget(self.stackedWidget, 1, 0, 1, 1)
        """
        #
        self.tabWidget.addTab(self.passInfoTab, _fromUtf8(""))
        self.paymentTab = QtGui.QWidget()
        self.paymentTab.setObjectName(_fromUtf8("paymentTab"))
        self.gridLayout_38 = QtGui.QGridLayout(self.paymentTab)
        self.gridLayout_38.setObjectName(_fromUtf8("gridLayout_38"))
        self.costGroupBox = QtGui.QGroupBox(self.paymentTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.costGroupBox.setFont(font)
        self.costGroupBox.setObjectName(_fromUtf8("costGroupBox"))
        self.gridLayout_15 = QtGui.QGridLayout(self.costGroupBox)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.costTextEdit = QtGui.QTextEdit(self.costGroupBox)
        self.costTextEdit.setReadOnly(True)
        self.costTextEdit.setObjectName(_fromUtf8("costTextEdit"))
        self.gridLayout_15.addWidget(self.costTextEdit, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.costGroupBox, 0, 0, 1, 1)
        self.creditGroupBox = QtGui.QGroupBox(self.paymentTab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.creditGroupBox.setFont(font)
        self.creditGroupBox.setObjectName(_fromUtf8("creditGroupBox"))
        self.gridLayout_13 = QtGui.QGridLayout(self.creditGroupBox)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.visaRadioButton = QtGui.QRadioButton(self.creditGroupBox)
        self.visaRadioButton.setObjectName(_fromUtf8("visaRadioButton"))
        self.gridLayout_13.addWidget(self.visaRadioButton, 0, 0, 1, 1)
        self.mcRadioButton = QtGui.QRadioButton(self.creditGroupBox)
        self.mcRadioButton.setObjectName(_fromUtf8("mcRadioButton"))
        self.gridLayout_13.addWidget(self.mcRadioButton, 0, 1, 1, 1)
        self.amexRadioButton = QtGui.QRadioButton(self.creditGroupBox)
        self.amexRadioButton.setObjectName(_fromUtf8("amexRadioButton"))
        self.gridLayout_13.addWidget(self.amexRadioButton, 0, 2, 1, 1)
        self.creditNameLabel = QtGui.QLabel(self.creditGroupBox)
        self.creditNameLabel.setObjectName(_fromUtf8("creditNameLabel"))
        self.gridLayout_13.addWidget(self.creditNameLabel, 1, 0, 1, 1)
        self.creditNameLineEdit = QtGui.QLineEdit(self.creditGroupBox)
        self.creditNameLineEdit.setObjectName(_fromUtf8("creditNameLineEdit"))
        self.gridLayout_13.addWidget(self.creditNameLineEdit, 1, 1, 1, 2)
        self.cardNumberLabel = QtGui.QLabel(self.creditGroupBox)
        self.cardNumberLabel.setObjectName(_fromUtf8("cardNumberLabel"))
        self.gridLayout_13.addWidget(self.cardNumberLabel, 2, 0, 1, 1)
        self.cardNumberLineEdit = QtGui.QLineEdit(self.creditGroupBox)
        self.cardNumberLineEdit.setObjectName(_fromUtf8("cardNumberLineEdit"))
        self.gridLayout_13.addWidget(self.cardNumberLineEdit, 2, 1, 1, 2)
        self.cvvLabel = QtGui.QLabel(self.creditGroupBox)
        self.cvvLabel.setObjectName(_fromUtf8("cvvLabel"))
        self.gridLayout_13.addWidget(self.cvvLabel, 3, 0, 1, 1)
        self.cvvLineEdit = QtGui.QLineEdit(self.creditGroupBox)
        self.cvvLineEdit.setObjectName(_fromUtf8("cvvLineEdit"))
        self.gridLayout_13.addWidget(self.cvvLineEdit, 3, 1, 1, 2)
        self.expLabel = QtGui.QLabel(self.creditGroupBox)
        self.expLabel.setObjectName(_fromUtf8("expLabel"))
        self.gridLayout_13.addWidget(self.expLabel, 4, 0, 1, 1)
        self.creditDateEdit = QtGui.QDateEdit(self.creditGroupBox)
        self.creditDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 3, 1), QtCore.QTime(0, 0, 0)))
        self.creditDateEdit.setCalendarPopup(True)
        self.creditDateEdit.setObjectName(_fromUtf8("creditDateEdit"))
        self.gridLayout_13.addWidget(self.creditDateEdit, 4, 1, 1, 1)
        self.gridLayout_38.addWidget(self.creditGroupBox, 1, 0, 1, 1)
        self.cancelPurchaseWidget = QtGui.QWidget(self.paymentTab)
        self.cancelPurchaseWidget.setMinimumSize(QtCore.QSize(0, 75))
        self.cancelPurchaseWidget.setObjectName(_fromUtf8("cancelPurchaseWidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.cancelPurchaseWidget)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.cancelButton = QtGui.QPushButton(self.cancelPurchaseWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.gridLayout_8.addWidget(self.cancelButton, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.purchaseButton = QtGui.QPushButton(self.cancelPurchaseWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.purchaseButton.setFont(font)
        self.purchaseButton.setObjectName(_fromUtf8("purchaseButton"))
        self.gridLayout_8.addWidget(self.purchaseButton, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_38.addWidget(self.cancelPurchaseWidget, 2, 0, 1, 1)
        self.tabWidget.addTab(self.paymentTab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRes = QtGui.QMenu(self.menubar)
        self.menuRes.setObjectName(_fromUtf8("menuRes"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionNewRes = QtGui.QAction(MainWindow)
        self.actionNewRes.setObjectName(_fromUtf8("actionNewRes"))
        self.actionCancelRes = QtGui.QAction(MainWindow)
        self.actionCancelRes.setObjectName(_fromUtf8("actionCancelRes"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuRes.addAction(self.actionNewRes)
        self.menuRes.addAction(self.actionCancelRes)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRes.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Fly Right Airlines", None))
        self.flyRightBannerLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Fly Right Airlines</span></p></body></html>", None))
        self.existingGroupBox.setTitle(_translate("MainWindow", "Existing Reservation", None))
        self.lastNameLabel.setText(_translate("MainWindow", "Last Name:", None))
        self.lookupButton.setText(_translate("MainWindow", "Lookup", None))
        self.resNumLabel.setText(_translate("MainWindow", "Reservation #:", None))
        self.firstNameLabel.setText(_translate("MainWindow", "First Name:", None))
        self.newResCommandLink.setText(_translate("MainWindow", "New Reservation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lookupTab), _translate("MainWindow", "Lookup", None))
        self.destGroupBox.setTitle(_translate("MainWindow", "Destination", None))
        self.fromLabel.setText(_translate("MainWindow", "From:", None))
        self.fromComboBox.setItemText(0, _translate("MainWindow", "Dallas, Texas (DFW)", None))
        self.fromComboBox.setItemText(1, _translate("MainWindow", "Denver, Colorado (DEN)", None))
        self.fromComboBox.setItemText(2, _translate("MainWindow", "Las Vegas, Nevada (LAS)", None))
        self.fromComboBox.setItemText(3, _translate("MainWindow", "Los Angeles, California (LAX)", None))
        self.fromComboBox.setItemText(4, _translate("MainWindow", "Miami, Florida (MIA)", None))
        self.fromComboBox.setItemText(5, _translate("MainWindow", "New York, New York (JFK)", None))
        self.fromComboBox.setItemText(6, _translate("MainWindow", "San Francisco, California (SFO)", None))
        self.toLabel.setText(_translate("MainWindow", "To:", None))
        self.toComboBox.setItemText(0, _translate("MainWindow", "Dallas, Texas (DFW)", None))
        self.toComboBox.setItemText(1, _translate("MainWindow", "Denver, Colorado (DEN)", None))
        self.toComboBox.setItemText(2, _translate("MainWindow", "Las Vegas, Nevada (LAS)", None))
        self.toComboBox.setItemText(3, _translate("MainWindow", "Los Angeles, California (LAX)", None))
        self.toComboBox.setItemText(4, _translate("MainWindow", "Miami, Florida (MIA)", None))
        self.toComboBox.setItemText(5, _translate("MainWindow", "San Francisco, California (SFO)", None))
        self.passGroupBox.setTitle(_translate("MainWindow", "Number of Passengers", None))
        self.dateTimeGroupBox.setTitle(_translate("MainWindow", "Date / Time", None))
        self.departDateLabel.setText(_translate("MainWindow", "Departure Date:", None))
        self.retDateLabel.setText(_translate("MainWindow", "Return Date:", None))
        self.departTimeLabel.setText(_translate("MainWindow", "Time:", None))
        self.returnTimeLabel.setText(_translate("MainWindow", "Time:", None))
        self.fareGroupBox.setTitle(_translate("MainWindow", "Fare Class", None))
        self.firstRadioButton.setText(_translate("MainWindow", "First Class", None))
        self.ecoRadioButton.setText(_translate("MainWindow", "Economy Plus", None))
        self.coachRadioButton.setText(_translate("MainWindow", "Coach", None))
        self.typeGroupBox.setTitle(_translate("MainWindow", "Type of Flight", None))
        self.nonStopRadioButton.setText(_translate("MainWindow", "Non Stop Flights", None))
        self.roundTripRadioButton.setText(_translate("MainWindow", "Round Trip", None))
        self.oneWayRadioButton.setText(_translate("MainWindow", "One Way", None))
        self.nextCommandLink.setText(_translate("MainWindow", "Next", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flightInfoTab), _translate("MainWindow", "Flight Info", None))
        self.departingGroupBox.setTitle(_translate("MainWindow", "Departing Flights", None))
        self.returnGroupBox.setTitle(_translate("MainWindow", "Return Flights", None))
        self.nextCommandLink_2.setText(_translate("MainWindow", "Next", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flightSelectTab), _translate("MainWindow", "Flight Selection", None))
        #start passanger info retranslate
        """
        self.backStackNavButton.setText(_translate("MainWindow", "<", None))
        self.fwdStackNavButton.setText(_translate("MainWindow", ">", None))
        self.passengerGroupBox.setTitle(_translate("MainWindow", "Passenger 1", None))
        self.seatGroupBox.setTitle(_translate("MainWindow", "Seat Selection", None))
        self.windowRadioButton.setText(_translate("MainWindow", "Window", None))
        self.aisleRadioButton.setText(_translate("MainWindow", "Aisle", None))
        self.centerRadioButton.setText(_translate("MainWindow", "Center", None))
        self.bagGroupBox.setTitle(_translate("MainWindow", "Checked Bags", None))
        self.specialGroupBox.setTitle(_translate("MainWindow", "Special Requests", None))
        self.handiCheckBox.setText(_translate("MainWindow", "Handicap", None))
        self.mealCheckBox.setText(_translate("MainWindow", "Meal Service", None))
        self.commentsLabel.setText(_translate("MainWindow", "Comments:", None))
        self.NameAddressGroupBox.setTitle(_translate("MainWindow", "Name/Address", None))
        self.passFirstLabel.setText(_translate("MainWindow", "First:", None))
        self.passCityLabel.setText(_translate("MainWindow", "City:", None))
        self.passAddressLabel.setText(_translate("MainWindow", "Address:", None))
        self.passMidLabel.setText(_translate("MainWindow", "Middle:", None))
        self.passLastLabel.setText(_translate("MainWindow", "Last:", None))
        self.passStateLabel.setText(_translate("MainWindow", "State:", None))
        self.passZipLabel.setText(_translate("MainWindow", "Zip:", None))
        self.mrsRadioButton.setText(_translate("MainWindow", "Mrs.", None))
        self.mrRadioButton.setText(_translate("MainWindow", "Mr.", None))
        self.msRadioButton.setText(_translate("MainWindow", "Ms.", None))"""
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.passInfoTab), _translate("MainWindow", "Passenger Info", None))
        #end passanger info retranslate
        self.costGroupBox.setTitle(_translate("MainWindow", "Cost", None))
        self.creditGroupBox.setTitle(_translate("MainWindow", "Credit Card", None))
        self.visaRadioButton.setText(_translate("MainWindow", "Visa", None))
        self.mcRadioButton.setText(_translate("MainWindow", "MasterCard", None))
        self.amexRadioButton.setText(_translate("MainWindow", "American Express", None))
        self.creditNameLabel.setText(_translate("MainWindow", "Name on card:", None))
        self.cardNumberLabel.setText(_translate("MainWindow", "Card Number:", None))
        self.cvvLabel.setText(_translate("MainWindow", "CVV Number:", None))
        self.expLabel.setText(_translate("MainWindow", "Expires:", None))
        self.cancelButton.setText(_translate("MainWindow", "Cancel", None))
        self.purchaseButton.setText(_translate("MainWindow", "Purchase", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.paymentTab), _translate("MainWindow", "Payment", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuRes.setTitle(_translate("MainWindow", "Reservation", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionNew.setText(_translate("MainWindow", "New Reservation", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))
        self.actionNewRes.setText(_translate("MainWindow", "New", None))
        self.actionCancelRes.setText(_translate("MainWindow", "Cancel", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As...", None))
        self.actionPrint.setText(_translate("MainWindow", "Print", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

import res_rc
